RajeshGogo/node-samples

- drive/quickstart/index.js
Implemented default authentication in drive_quickstart
> Drive: Implemented default authentication

- apps-script/quickstart/index.js
- calendar/quickstart/index.js
- classroom/quickstart/index.js
- docs/quickstart/index.js
- drive/activity-v2/index.js
- gmail/quickstart/index.js
- people/quickstart/index.js
- sheets/quickstart/index.js
- slides/quickstart/index.js
- tasks/quickstart/index.js
Implemented default authentication in all the Quickstarts
> Implemented default authentication 

- drive/snippets/drive_v2/appdata_snippets/fetch_appdata_folder.js
- drive/snippets/drive_v2/appdata_snippets/list_appdata.js
- drive/snippets/drive_v2/appdata_snippets/upload_appdata.js
Implemented default auth in upload_appdata, fetch_appdata_folder, list_appdata region tags.
upload_appdata : Insert a file in the application data folder and prints file Id.
fetch_appdata_folder : List out application data folder and prints folder ID
list_appdata : List all files inserted in the application data folder
> Drive: Appdata Snippet

- sheets/snippets/sheets_batch_get_values.js
- sheets/snippets/sheets_batch_update.js
- sheets/snippets/sheets_batch_update_values.js
- sheets/snippets/sheets_create.js
- sheets/snippets/sheets_get_values.js
- sheets/snippets/sheets_update_values.js
Implemented default auth for: 
sheets_create, sheets_get_values, sheets_batch_get_values,
sheets_batch_update, sheets_update_values, sheets_batch_update_values
sheets_create: Create a google spreadsheet
sheets_get_values: Gets cell values from a Spreadsheet
sheets_batch_get_values: Batch gets cell values from a Spreadsheet
sheets_batch_update: Updates the Spreadsheet title. Finds and replaces a string in the sheets
sheets_update_values: Updates values in a Spreadsheet
sheets_batch_update_values: Batch Updates values in a Spreadsheet
> Sheets Snippets

- drive/snippets/drive_v2/change_snippets/fetch_changes.js
- drive/snippets/drive_v2/change_snippets/fetch_start_page_token.js
Drive change snippets
Fetch_changes : Retrieve the list of changes for the currently authenticated user.
Fetch_start_page_token : Retrieve page token for the current state of the account.
> Drive: change_snippets

- drive/snippets/drive_v2/appdata_snippets/fetch_appdata_folder.js
- drive/snippets/drive_v2/appdata_snippets/list_appdata.js
- drive/snippets/drive_v2/appdata_snippets/upload_appdata.js
async/await used instead on callback
> Drive-v2: Appdata snippet

- drive/snippets/drive_v2/change_snippets/fetch_changes.js
- drive/snippets/drive_v2/change_snippets/fetch_start_page_token.js
async/await used instead on callback
> Drive-v2: Change snippet

- drive/snippets/drive_v3/appdata_snippets/fetch_appdata_folder.js
- drive/snippets/drive_v3/appdata_snippets/list_appdata.js
- drive/snippets/drive_v3/appdata_snippets/upload_appdata.js
Implemented default auth and used async/await instead on callback.
> Drive-v3: Appdata snippet

- drive/quickstart/index.js
- sheets/snippets/sheets_append_values.js
- sheets/snippets/sheets_batch_get_values.js
- sheets/snippets/sheets_batch_update.js
- sheets/snippets/sheets_batch_update_values.js
- sheets/snippets/sheets_conditional_formatting.js
- sheets/snippets/sheets_create.js
- sheets/snippets/sheets_get_values.js
- sheets/snippets/sheets_pivot_table.js
- sheets/snippets/sheets_update_values.js
Implemented default authentication, async/await with try catch instead of call back for:
sheets_create, sheets_batch_update, sheets_get_values,
sheets_batch_get_values, sheets_update_values, sheets_batch_update_values,
sheets_append_values, sheets_pivot_tables, sheets_conditional_formatting
> Updated sheets snippets

- drive/quickstart/index.js
- slides/snippets/slides_copy_presentation.js
- slides/snippets/slides_create_image.js
- slides/snippets/slides_create_presentation.js
- slides/snippets/slides_create_slide.js
- slides/snippets/slides_create_textbox_with_text.js
Added default authentication, async/await and try catch to:
slides_copy_presentation, slides_create_image, slides_create_presentation,
slides_create_slide, slides_create_textbox_with_text
> Updates Slides snippets

- drive/quickstart/index.js
- slides/snippets/slides_image_merging.js
- slides/snippets/slides_simple_text_replace.js
- slides/snippets/slides_text_merging.js
- slides/snippets/slides_text_style_update.js
Updated slide snippets
Added default authentication, async/await and try catch to:
slides_image_merging, slides_simple_text_replace,
slides_text_merging, and slides_text_style_update
> Slides snippets 2

- drive/snippets/drive_v3/appdata_snippets/fetch_appdata_folder.js
- drive/snippets/drive_v3/appdata_snippets/list_appdata.js
- drive/snippets/drive_v3/appdata_snippets/upload_appdata.js
> Drive v3 appdata

- drive/snippets/drive_v2/file snippets/create_folder.js
- drive/snippets/drive_v2/file snippets/create_shortcut.js
- drive/snippets/drive_v2/file snippets/search_file.js
- drive/snippets/drive_v2/file snippets/upload_basic.js
- drive/snippets/drive_v2/file snippets/upload_to_folder.js
- drive/snippets/drive_v2/file snippets/upload_with_conversion.js
Async/await used instead on callback and implemented default authentication.
> Drive:file snippet

- drive/snippets/drive_v3/appdata_snippets/fetch_appdata_folder.js
- drive/snippets/drive_v3/appdata_snippets/list_appdata.js
- drive/snippets/drive_v3/appdata_snippets/upload_appdata.js
fixed lint issues in Appdata snippet
Fixes # (230522234)
> Fixed lint issues in Appdata snippet

- drive/snippets/drive_v2/file snippets/download_file.js
- drive/snippets/drive_v2/file snippets/export_pdf.js
- drive/snippets/drive_v2/file snippets/move_file_to_folder.js
- drive/snippets/drive_v2/file snippets/share_file.js
- drive/snippets/drive_v2/file snippets/touch_file.js
Drive: share_file, move_file_to_folder, download_file, export_pdf, touch_file
Fixes # (230522234)
> Drive: share_file, move_file_to_folder, download_file, export_pdf, touch_file

- drive/snippets/drive_v2/drive_snippets/create_drive.js
- drive/snippets/drive_v2/drive_snippets/recover_drives.js
Drive snippet
create_drive: create drive.
recover_drives: finds all the drives with no organizer and adds one. 
Fixes # (230430685)
> Drive: drive snippet

- sheets/snippets/sheets_append_values.js
- sheets/snippets/sheets_batch_get_values.js
- sheets/snippets/sheets_batch_update.js
- sheets/snippets/sheets_batch_update_values.js
- sheets/snippets/sheets_conditional_formatting.js
- sheets/snippets/sheets_create.js
- sheets/snippets/sheets_get_values.js
- sheets/snippets/sheets_pivot_table.js
- sheets/snippets/sheets_update_values.js
- sheets/snippets/test/helpers.js
- sheets/snippets/test/snippets.spec.js
- sheets/snippets/test/test_sheets_batch_get_values.js
- sheets/snippets/test/test_sheets_batch_update.js
- sheets/snippets/test/test_sheets_create.js
- sheets/snippets/test/test_sheets_update_values.js
adds return statements to sheets snippets, updates sheets snippets unit tests to implement default authentication,
adds test files for: sheets_batch_get_values, sheets_batch_update, sheets_create, and sheets_update_values
Fixes # (bug ID)
> Sheets snippets tests

- drive/snippets/drive_v3/drive_snippets/create_drive.js
- drive/snippets/drive_v3/drive_snippets/recover_drives.js
Drive snippet
create_drive: create drive.
recover_drives: finds all the drives with no organizer and adds one.
Fixes # (230430685)
> Drive v3 drive snippets

- drive/snippets/drive_v3/file_snippets/create_folder.js
- drive/snippets/drive_v3/file_snippets/create_shortcut.js
- drive/snippets/drive_v3/file_snippets/download_file.js
Drive-v3 file snippets
create_folder : Create a folder
create_shortcut : Create a third party shortcut
download_file : Downloads file
Fixes # (230430685)
> Drive: Create_folder, create_shortcut, download_file

- drive/snippets/drive_v3/file_snippets/export_pdf.js
- drive/snippets/drive_v3/file_snippets/move_file_to_folder.js
- drive/snippets/drive_v3/file_snippets/search_file.js
- drive/snippets/drive_v3/file_snippets/share_file.js
- drive/snippets/drive_v3/file_snippets/touch_file.js
- drive/snippets/drive_v3/file_snippets/upload_basic.js
Drive-v3 file_snippets
export_pdf(Bug_id-232039687) : Download a document file in Pdf format.
move_file_to_folder(Bug_id-232040050) : Move one file to specified folder.
search_file(Bug_id-232177275) : Search a file in drive location
share_file(Bug_id-232177364) : Batch permission modification
upload_basic(Bug_id-232177235) : Insert a new file
touch_file(Bug_id-232177411) : Change file's modification timestamp
> Drive v3: file snippet

- sheets/snippets/test/test_sheets_batch_get_values.js
- sheets/snippets/test/test_sheets_batch_update.js
- sheets/snippets/test/test_sheets_create.js
- sheets/snippets/test/test_sheets_update_values.js
Cleaning up and removing redundant promises, delays, and wrappers in sheets snippets test files.
Fixes # (232442897, 232441270, 232442903, 232442904)
> Updates Sheets Snippets unit tests:

- drive/snippets/drive_v3/file_snippets/upload_to_folder.js
- drive/snippets/drive_v3/file_snippets/upload_with_conversion.js
Description
Drive-v3 file_snippet
Upload_to_folder(Bug_id-232177413) : Upload file with conversion.
Upload_with_conversion(Bug_id-232177413) : Upload a file to the specified folder.
> Drive v3 : file_snippet

- sheets/snippets/test/helpers.js
- sheets/snippets/test/test_sheets_append_values.js
- sheets/snippets/test/test_sheets_batch_get_values.js
- sheets/snippets/test/test_sheets_batch_update.js
- sheets/snippets/test/test_sheets_batch_update_values.js
- sheets/snippets/test/test_sheets_conditional_formatting.js
- sheets/snippets/test/test_sheets_create.js
- sheets/snippets/test/test_sheets_get_values.js
- sheets/snippets/test/test_sheets_pivot_table.js
- sheets/snippets/test/test_sheets_update_values.js
adds files for sheets snippets tests: test_sheets_append_values.js, test_sheets_batch_update_values.js, 
test_sheets_conditional_formatting.js, test_sheets_get_values.js,
test_sheets_pivot_table.js.
and add default authentication,
and fixes an issue where the last test spreadsheet was not being deleted
Fixes # (232558808, 232556643, 232559308, 232559310, 232558816)
> Updates Sheets Snippets Unit Tests

- drive/snippets/drive_v2/team_drive_snippets/create_team_drive.js
- drive/snippets/drive_v2/team_drive_snippets/recover_team_drives.js
- drive/snippets/drive_v3/team_drive_snippets/create_team_drive.js
- drive/snippets/drive_v3/team_drive_snippets/recover_team_drives.js
Drive v2,v3 team drive snippets:
create_team_drive : create a drive
recover_team_drives : find all shared team drive with out a organizer and add one
> Drive: team_drive_snippets v2,v3

- adminSDK/directory/index.js
- adminSDK/reports/index.js
- adminSDK/reseller/index.js
Admin sdk :-
directory quickstart(Bug_id-232890953) : Lists the first 10 users in the domain
report quickstart(Bug_id-232891123) : Lists the last 10 login events for the domain
reseller quickstart(Bug_id-232891255) :Lists the first 10 subscriptions you manage
> Admin_sdk- Implemented default auth

- apps-script/execute/index.js
Apps script:
apps_script_api_execute(Bug_id-232890951) : Call an Apps Script function to list the folders in the user's root Drive folder.
> Apps script : execute

- drive/snippets/drive_v3/appdata_snippets/fetch_appdata_folder.js
- drive/snippets/drive_v3/appdata_snippets/list_appdata.js
- drive/snippets/drive_v3/appdata_snippets/upload_appdata.js
- drive/snippets/drive_v3/change_snippets/fetch_changes.js
- drive/snippets/drive_v3/change_snippets/fetch_start_page_token.js
- drive/snippets/test/helpers.js
- drive/snippets/test/test_drive_v3_fetch_appdata_folder.js
- drive/snippets/test/test_drive_v3_fetch_changes.js
- drive/snippets/test/test_drive_v3_fetch_start_page_token.js
- drive/snippets/test/test_drive_v3_list_appdata.js
- drive/snippets/test/test_drive_v3_upload_appdata.js
Adds unit test files: test_drive_v3_fetch_appdata_folder.js, test_drive_v3_fetch_changes.js, test_drive_v3_fetch_start_page_token.js, test_drive_v3_list_appdata.js, test_drive_v3_upload_appdata.js
Fixes # (234607932, 234608041, 234608575, 234608580, 234609396)
> Drive v3 Unit Tests:

- drive/snippets/test/test_drive_v2_create_drive.js
- drive/snippets/test/test_drive_v2_create_folder.js
- drive/snippets/test/test_drive_v2_create_shortcut.js
- drive/snippets/test/test_drive_v2_download_file.js
- drive/snippets/test/test_drive_v2_export_pdf.js
- drive/snippets/test/test_drive_v2_fetch_appdata_folder.js
- drive/snippets/test/test_drive_v2_fetch_changes.js
- drive/snippets/test/test_drive_v2_fetch_start_page_token.js
- drive/snippets/test/test_drive_v2_list_appdata.js
- drive/snippets/test/test_drive_v2_move_file_to_folder.js
- drive/snippets/test/test_drive_v2_recover_drives.js
- drive/snippets/test/test_drive_v2_upload_appdata.js
Drive-v2 Unit test cases
create_folder(Bug-234678881)
create_shortcut(Bug-234678885)
download_file(Bug-234678886)
export_pdf(Bug-234679028)
move_file_to_folder(Bug-234679038)
fetch_appdata_folder(Bug-234679017)
upload_appdata(Bug-234679211)
list_appdata_folder(Bug-234679037)
fetch_changes(Bug-234679051)
fetch_start_page_token(Bug-234679031)
create_drive(Bug-234678581) 
recover_drives(Bug-234679042)
> Drive-v2 Unit test

- drive/snippets/drive_v3/drive_snippets/create_drive.js
- drive/snippets/drive_v3/drive_snippets/recover_drives.js
- drive/snippets/drive_v3/file_snippets/create_folder.js
- drive/snippets/drive_v3/file_snippets/create_shortcut.js
- drive/snippets/test/test_drive_v3_create_drive.js
- drive/snippets/test/test_drive_v3_create_folder.js
- drive/snippets/test/test_drive_v3_create_shortcut.js
- drive/snippets/test/test_drive_v3_recover_drives.js
adds unit test file:
test_drive_v3_create_drive.js, test_drive_v3_create_folder.js, test_drive_v3_create_shortcut.js, test_drive_v3_recover_drives.js
Fixes # (234771018, 234771192, 234772716, 234772722)
> Drive v3 Unit Tests

- drive/snippets/drive_v3/file_snippets/download_file.js
- drive/snippets/drive_v3/file_snippets/export_pdf.js
- drive/snippets/drive_v3/file_snippets/move_file_to_folder.js
- drive/snippets/drive_v3/file_snippets/search_file.js
- drive/snippets/drive_v3/file_snippets/share_file.js
- drive/snippets/drive_v3/file_snippets/touch_file.js
- drive/snippets/drive_v3/file_snippets/upload_basic.js
- drive/snippets/drive_v3/file_snippets/upload_to_folder.js
- drive/snippets/drive_v3/file_snippets/upload_with_conversion.js
- drive/snippets/test/test_drive_v3_download_file.js
- drive/snippets/test/test_drive_v3_export_pdf.js
- drive/snippets/test/test_drive_v3_move_file_to_folder.js
- drive/snippets/test/test_drive_v3_search_file.js
- drive/snippets/test/test_drive_v3_share_file.js
- drive/snippets/test/test_drive_v3_touch_file.js
- drive/snippets/test/test_drive_v3_upload_basic.js
- drive/snippets/test/test_drive_v3_upload_to_folder.js
- drive/snippets/test/test_drive_v3_upload_with_conversion.js
Added Unit Test files for: 
export_pdf, download_file, search_file, share_file, touch_file, upload_basic, upload_to_folder, upload_with_conversion.js, move_file_to_folder.
Fixes # (234771086, 234771415, 234771378, 234771458, 234771469, 234771598, 234771706, 234771892, 234771902)
> Drive v3 snippets unit test

- drive/snippets/test/helpers.js
- drive/snippets/test/test_drive_v2_search_file.js
- drive/snippets/test/test_drive_v2_share_file.js
- drive/snippets/test/test_drive_v2_touch_file.js
- drive/snippets/test/test_drive_v2_upload_basic.js
- drive/snippets/test/test_drive_v2_upload_to_folder.js
- drive/snippets/test/test_drive_v2_upload_with_conversion.js
Drive-v2 unit test cases:
search_file(Bug_id-235184950)
share_file(Bug_id-235184952)
touch_file(Bug_id-235184936)
upload_basic(Bug_id-235184939)
upload_to_folder(Bug_id-235184942)
upload_with_conversion(Bug_id-235184957)
> Drive v2 UT
